core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from farmflow.views import CustomLoginView  
from farmflow.forms import LoginForm
from django.urls import re_path
from farmflow.views import ResetPasswordView, ChangePasswordView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('farmflow.urls')),
    path('agromonitoring/', include('agromonitoring.urls')),
    path('farmerdata/', include('farmerdata.urls')),
    path('', include('whatsapp.urls')),
    path('', include('ussd.urls')),

    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),

    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

    path('password-change/', ChangePasswordView.as_view(), name='password_change'),

    re_path(r'^oauth/', include('social_django.urls', namespace='social')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farmflow/urls.py
from django.urls import path
from .views import index, RegisterView, profile, edit_profile, identify_plant, LigthNav, Chart, Table, NotFound, Unauthorised, ServerError

urlpatterns = [
    path('', index, name='home'),
    path('register/', RegisterView.as_view(), name='users-register'),
    path('profile/', profile, name='users-profile'),
    path('edit/profile/', edit_profile, name='edit-profile'),
    path('dashboard/layout-static/', identify_plant, name='identify-plant'),
    path('dashboard/layout-sidenav-light/', LigthNav, name='light-nav'),
    path('dashboard/chart/', Chart, name='chart'),
    path('dashboard/table/', Table, name='table'),
    path('dashboard/404/', NotFound, name='404'),
    path('dashboard/401/', Unauthorised, name='401'),
    path('dashboard/500/', ServerError, name='500'),

]

farmflow/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from phonenumber_field.modelfields import PhoneNumberField
import uuid
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.db.models import Q


# Create your models here.
class Cluster(models.Model):
    name = models.CharField(max_length=255, unique=True)
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class ProducerGroup(models.Model):
    name = models.CharField(max_length=255, unique=True)
    cluster = models.ForeignKey(Cluster, on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='producer_groups')

    def __str__(self):
        return f"{self.name} ({self.cluster})"

class ValueChainChoice(models.Model):
    VALUE_CHAIN_CHOICE = [
        ("Poultry", "Poultry"),
        ("Vegetable", "Vegetable"),
        ("Herbs", "Herbs"),
        ("Dairy", "Dairy"),

    ]
    name = models.CharField(max_length=255, choices=VALUE_CHAIN_CHOICE, unique=True)


    def __str__(self):
        return self.name

class SoilTestResult(models.Model):
    RESPONSES = [
        ("Y", "YES"),
        ("N", "NO"),
    ]
    TYPE_CHOICES = [
        ("Complete", "Complete"),
        ("Partial", "Partial"),
    ]
    type = models.CharField(max_length=255, choices=TYPE_CHOICES)
    done = models.CharField(max_length=255, choices=RESPONSES)
    reason = models.CharField(max_length=255, blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['type', 'done'], name='unique_test_result'),
            models.CheckConstraint(
                check=Q(done='Y') | ~Q(done='N') | ~Q(reason=''),
                name='reason_required_for_no',
            ),
        ]

    def __str__(self):
        return f"{self.type} - {self.done}"
    
    
class InputUsed(models.Model):
    AMOUNT_CHOICES = [
        ('kg', 'kg'),
        ('litres', 'litres'),
    ]
    TYPE_CHOICES = [
        ('Fertilizer', 'Fertilizer'),
        ('Pesticides', 'Pesticides'),
    ]
    type = models.CharField(max_length=255, choices=TYPE_CHOICES)
    value_chain = models.ForeignKey(ValueChainChoice, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    amount = models.CharField(max_length=255, choices=AMOUNT_CHOICES)
    farms = models.ManyToManyField('Farm', through='FarmInputUsed')

    def __str__(self):
        return f"{self.name} ({self.amount} of {self.type})"   

class FarmingType(models.Model):
    FARMING_CHOICES = [
        ("Outdoor", "Outdoor"),
        ("Greenhouse", "Greenhouse"),

    ]
    type = models.CharField(max_length=255, choices=FARMING_CHOICES, unique=True)

    def __str__(self):
        return self.type

class WaterSource(models.Model):
    WATER_SOURCE_CHOICES = [
        ("Borehole", "Borehole"),
        ("River", "River"),
        ("Dam", "Dam"),
        ("Rain", "Rain"),
        ("Swamp", "Swamp"),
        ('Other', 'other')
    ]
    type = models.CharField(max_length=255, choices=WATER_SOURCE_CHOICES, unique=True)

    def __str__(self):
        return self.type

class Farm(models.Model):
    owner = models.ForeignKey(User, related_name='farmer', on_delete=models.CASCADE)
    location = models.CharField(max_length=55)
    crops = models.ManyToManyField('Crop', related_name='crops', blank=True)
    length = models.PositiveIntegerField(default=0)
    width = models.PositiveIntegerField(default=0)
    is_leased = models.BooleanField(default=False)
    soil_test = models.ForeignKey(SoilTestResult, on_delete=models.CASCADE)
    water_source = models.ForeignKey(WaterSource, on_delete=models.CASCADE)
    farming_type = models.ForeignKey(FarmingType, on_delete=models.CASCADE)
    input_used = models.ManyToManyField('InputUsed', through='FarmInputUsed')
    value_chains = models.ManyToManyField(ValueChainChoice, blank=True)
    STATUS_CHOICES = [
        ('Pending', 'Pending Approval'),
        ('Approved', 'Approved'),
        ('Rejected', 'Rejected')
    ]
    approval_status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Pending')

    @classmethod
    def my_farms(cls, user_id):
        return cls.objects.filter(owner__id=user_id)

    def __str__(self):
        value_chain_names = ', '.join([value_chain.name for value_chain in self.value_chains.all()])
        crop_names = [crop.name for crop in self.crops.all()]
        crop_str = crop_names[0] if len(crop_names) == 1 else ', '.join(crop_names)
        return f"{self.owner.get_full_name()}'s farm ({value_chain_names}) growing {crop_str} in {self.location} - {self.approval_status}"

class Profile(models.Model):
    GENDER_CHOICES =[
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email= models.EmailField(max_length=255, unique=True, blank=True, null=True)
    avatar = CloudinaryField('image', default='https://res.cloudinary.com/fevercode/image/upload/v1654534329/default_n0r7rf.png')
    bio = models.TextField(max_length=500, default='This is my bio')
    name = models.CharField(max_length=255, blank=True)
    producer_group = models.ForeignKey(ProducerGroup, on_delete=models.SET_NULL, null=True, blank=True)
    gender = models.CharField(max_length=255, choices=GENDER_CHOICES)
    id_number = models.PositiveBigIntegerField(unique=True, blank=True, null=True)
    phone_number = PhoneNumberField(unique=True, null=True, blank=True)
    plot_size = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False, default=0)
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE, null=True)
      
    def create_profile(self):
        self.save()
        
    def update_profile(self, new_bio):
        self.bio = new_bio
        self.save()
    
    def save(self, *args, **kwargs):
        self.name = f"{self.user.first_name} {self.user.last_name}"  # set the name as the user's first and last name
        self.email = self.user.email
        super().save(*args, **kwargs)  # call the original save method

    def __str__(self):
        return f"{self.user.username} ({self.producer_group}) Profile"

class Crop(models.Model):
    name = models.CharField(max_length=55,unique=True)
    description = models.CharField(max_length=255)
    value_chain = models.ForeignKey(ValueChainChoice, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} ({self.value_chain})"
    
class FarmInputUsed(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)
    input_used = models.ForeignKey(InputUsed, on_delete=models.CASCADE)
    quantity_used = models.PositiveSmallIntegerField(blank=True, null=True)
    crop = models.ForeignKey(Crop, on_delete=models.CASCADE)
    date_used =  models.DateField()

    def __str__(self):
        return f"{self.farm} used {self.quantity_used} {self.input_used.amount} of {self.input_used.name} on {self.date_used}"

class CropProductionStage(models.Model):
    planted_date = models.DateField()
    harvested_date = models.DateField()
    ploughing = models.DateField()
    weeding = models.DateField()
    harvesting = models.DateField()
    crop = models.ForeignKey(Crop, on_delete=models.CASCADE)
    inputs = models.ManyToManyField(InputUsed, blank=True)
    farm = models.ForeignKey(Farm, on_delete=models.CASCADE)

    def clean(self):
        if self.harvested_date < self.planted_date:
            raise ValidationError('Harvested date cannot be before planted date')

        if self.harvesting > self.harvested_date:
            raise ValidationError('Harvesting date cannot be greater than harvested date')

        if self.harvesting > timezone.now().date():
            raise ValidationError('Harvesting date cannot be in the future')

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.crop} production stage at {self.farm} ({self.planted_date} - {self.harvested_date})"
    
class Produce(models.Model):
    GRADE_CHOICES = [
    ('Grade A', 'Grade A'),
    ('Grade B', 'Grade B'),
    ('Grade C', 'Grade C'),
    ]
    farmer = models.ForeignKey(Profile, on_delete=models.CASCADE)
    type = models.CharField(max_length=255)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    grade = models.CharField(max_length=255, choices=GRADE_CHOICES)
    production_date = models.DateField()
    value_chain = models.ForeignKey(ValueChainChoice, on_delete=models.CASCADE)
    # Add a field to track the status of the produce (e.g., harvested, in transit, at the market, sold).
    STATUS_CHOICES = [
        ('Harvested', 'Harvested'),
        ('In Transit', 'In Transit'),
        ('At the Market', 'At the Market'),
        ('Sold', 'Sold'),
    ]
    status = models.CharField(max_length=255, choices=STATUS_CHOICES)
    # Add a field to track the location of the produce, such as the name of the market or the name of the buyer.
    location = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.type} - {self.quantity}kg of {self.grade} by ({self.farmer.user.username}) on {self.production_date} currently {self.status}'
    
class Tag(models.Model):
    tag_id = models.CharField(max_length=36, unique=True, editable=False)
    farmer = models.ForeignKey(Profile, on_delete=models.CASCADE)
    produce = models.ForeignKey(Produce, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, default='Harvested')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if not self.tag_id:
            self.tag_id = str(uuid.uuid4())

    def save(self, *args, **kwargs):
        if self.produce:
            self.status = self.produce.status
        super().save(*args, **kwargs)

    def __str__(self):

farmflow/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import *
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError

from django.core.exceptions import ValidationError

class RegisterForm(UserCreationForm):
    # fields we want to include and customize in our form
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              'class': 'form-control',
                                                              }))
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Email already exists")
        return email



class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
 
    # phone_number = forms.IntegerField(validators=[RegexValidator(regex='^[0-9]{10}$')],
    #                              required=True,
    #                              widget=forms.TextInput(attrs={'placeholder': 'Phone Number',
    #                                                            'class': 'form-control',
    #                                                            }))
    
    
    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

class PlantImageForm(forms.Form):
    image = forms.ImageField()

farmflow/templates/bootstrap/401.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>404 Error - Farm Share Kenya</title>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-4">
                                    <h1 class="display-1">401</h1>
                                    <p class="lead">Unauthorized</p>
                                    <p>Access to this resource is denied.</p>
                                    <a href="{% url 'home' %}">
                                        <i class="fas fa-arrow-left me-1"></i>
                                        Return to Dashboard
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutError_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; <a href="https://farmshare.co.ke/" >Farm Share Kenya Ltd 2023</a></div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

farmflow/templates/bootstrap/charts.html
{% extends "bootstrap/base.html" %}
{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">Charts</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Dashboard</a></li>
        <li class="breadcrumb-item active">Charts</li>
    </ol>
    <!-- <div class="card mb-4">
        <div class="card-body">
            Chart.js is a third party plugin that is used to generate the charts in this template. The charts below have
            been customized - for further customization options, please visit the official
            <a target="_blank" href="https://www.chartjs.org/docs/latest/">Chart.js documentation</a>
            .
        </div>
    </div> -->
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-chart-area me-1"></i>
            Area Chart Example
        </div>
        <div class="card-body"><canvas id="myAreaChart" width="100%" height="30"></canvas></div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-chart-bar me-1"></i>
                    Bar Chart Example
                </div>
                <div class="card-body"><canvas id="myBarChart" width="100%" height="50"></canvas></div>
                <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-chart-pie me-1"></i>
                    Pie Chart Example
                </div>
                <div class="card-body"><canvas id="myPieChart" width="100%" height="50"></canvas></div>
                <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

farmflow/templates/bootstrap/index.html
{% extends "bootstrap/base.html" %}
{% block content %}
<div class="container-fluid px-4">
    <h1 class="mt-4">{{user.username}}'s Dashboard</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item active">Dashboard</li>
    </ol>
    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary text-white mb-4">
                <div class="card-body">Value Chains: <h2>{{ value_chain_count }}</h2>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="{% url 'add_value_chain' %}">Add Value Chain</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-warning text-white mb-4">
                <div class="card-body">Farms: <h2>{{ farm_count }}</h2>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="{% url 'add_farm' %}">Add Farm</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-success text-white mb-4">
                <div class="card-body">Crops: <h2>{{total_crop_count}}</h2>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="{% url 'add_crop' %}">Add Crop</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6">
            <div class="card bg-danger text-white mb-4">
                <div class="card-body">Produce: <h2>{{ produce_count }}</h2>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <!-- <a class="small text-white stretched-link" href="#">Add Produce</a> -->
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-crop me-1"></i>
                    {{user.username}}'s Crops
                </div>
                <h2 class="ms-2">List of Crops</h2>
                <!-- <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div> -->
                {% if crops %}
                {% for crop in crops %}
                <h3 class="ms-2">{{ crop.name }}</h3>
                <p class="ms-2">{{ crop.description }}</p>
                <p class="ms-2"> <strong>Value Chain:</strong> {{ crop.value_chain }}</p>
                {% endfor %}
                {% else %}
                <p class="text-center">No crops found.</p>
                {% endif %}
            </div>
        </div>
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-chart-bar me-1"></i>
                    {{user.username}}'s Farms
                </div>
                <!-- <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div> -->
                <h2 class="ms-2">List of Farms</h2>
                <p class="ms-2">Farms awaiting approval: {{ pending_approval_count }}</p>
                {% if farms %}
                <ul>
                    {% for farm in farms %}
                    <li>
                        <strong>{{ farm.owner.get_full_name }}</strong> owns a farm in <span class="text-bg-info">{{ farm.location }}</span> 
                        that
                        grows:
                        {% if farm.crops.count == 1 %}
                        {{ farm.crops.first.name }}
                        {% else %}
                        <ul>
                            {% for crop in farm.crops.all %}
                            <li> {{ crop.name }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}
                        {% if farm.value_chains.all %}
                        <p><strong>Value Chain:</strong>
                            {% for value_chain in farm.value_chains.all %}{{ value_chain.name }},
                            {% endfor %}</p>
                        {% endif %}
                        {% if farm.soil_test %}
                        <p><strong>Soil Test Result:</strong> {{ farm.soil_test }}</p>
                        {% endif %}
                        {% if farm.water_source %}
                        <p><strong>Water Source:</strong> {{ farm.water_source }}</p>
                        {% endif %}
                        {% if farm.farming_type %}
                        <p><strong>Farming Type:</strong> {{ farm.farming_type }}</p>
                        {% endif %}
                        {% if farm.input_used.all %}
                        <p><strong>Input Used:</strong></p>
                        <ul>
                            {% for farm_input_used in farm.farminputused_set.all %}
                            <li>{{ farm_input_used.input_used.name }} ({{ farm_input_used.quantity_used }}
                                {{ farm_input_used.input_used.amount }})</li>
                            {% endfor %}

                        </ul>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                <p class="text-center">No farms found.</p>
                {% endif %}

            </div>
        </div>
    </div>
    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            {{user.username}}'s Crop Production Stages
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>Crop</th>
                        <th>Planted</th>
                        <th>Harvested</th>
                        <th>Ploughing</th>
                        <th>Weeding</th>
                        <th>Inputs used</th>
                        <!--<th>Farm</th> -->
                    </tr>
                </thead>
                <!-- <tfoot> -->
                <!-- <tr> -->
                <!-- <th>Crop</th> -->
                <!-- <th>Planted</th> -->
                <!-- <th>Harvested</th> -->
                <!-- <th>Ploughing</th> -->
                <!-- <th>Weeding</th> -->
                <!-- <th>Inputs used</th> -->
                <!--<th>Farm</th> -->
                <!-- </tr> -->
                <!-- </tfoot> -->
                <tbody>
                    {% for production_stage in production_stages %}
                    <tr>
                        <td>{{ production_stage.crop }}</td>
                        <td>{{ production_stage.planted_date }}</td>
                        <td>{{ production_stage.harvested_date }}</td>
                        <td>{{ production_stage.ploughing }}</td>
                        <td>{{ production_stage.weeding }}</td>
                        <td>{% for input_used in production_stage.inputs.all %}
                {{ input_used.name }} ({{ input_used.amount }})
                {% if not forloop.last %}, {% endif %}
            {% endfor %}</td>
                        <!-- <td>{{ production_stage.farm }}</td> -->
                    </tr>
                    {% endfor %}
                    <!--  -->
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

farmflow/templates/bootstrap/upload.html
{% extends "bootstrap/base.html" %}
{% block title %}Crop Health Checker{% endblock %}
{% block content %}
            <div class="container-fluid px-4">
                <h1 class="mt-4">Check your crop health</h1>
                <ol class="breadcrumb mb-4">
                    <li class="breadcrumb-item"><a href="{% url 'home' %}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Crop Health</li>
                </ol>
                <div class="card mb-4">
                    <div class="card-body">
                        <p class="mb-0">
                            <h3>Upload crop image for health check</h3>
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit">Check</button>
                            </form>
                        </p>
                    </div>
                </div>
            </div>
{% endblock content %}